server {
    listen 8080;
    server_name abdullah.aurixcollection.com;
    root /var/www/abdullah;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.3-fpm.sock; }
    location ~ /\.ht { deny all; }
    error_log /var/log/nginx/abdullah-error.log;
    access_log /var/log/nginx/abdullah-access.log;
}

server {
    listen 8080;
    server_name aftab.aurixcollection.com;
    root /var/www/aftab;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.3-fpm.sock; }
    location ~ /\.ht { deny all; }
    error_log /var/log/nginx/aftab-error.log;
    access_log /var/log/nginx/aftab-access.log;
}

server {
    listen 8080;
    server_name ahmad.aurixcollection.com;
    root /var/www/ahmad;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.3-fpm.sock; }
    location ~ /\.ht { deny all; }
    error_log /var/log/nginx/ahmad-error.log;
    access_log /var/log/nginx/ahmad-access.log;
}

server {
    listen 8080;
    server_name malik.aurixcollection.com;
    root /var/www/malik;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.3-fpm.sock; }
    location ~ /\.ht { deny all; }
    error_log /var/log/nginx/malik-error.log;
    access_log /var/log/nginx/malik-access.log;
}

server {
    listen 8080;
    server_name uzair.aurixcollection.com;
    root /var/www/uzair;
    index index.php index.html;
    location / { try_files $uri $uri/ /index.php?$args; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.3-fpm.sock; }
    location ~ /\.ht { deny all; }
    error_log /var/log/nginx/uzair-error.log;
    access_log /var/log/nginx/uzair-access.log;
}
